### ISSUE TITLE
Slow AF, & Articles Never Load - What am I doing wrong?

### ISSUE THREAD

**Issue by sanctimoniousape** [ksh-b/raven#19]
I've disabled my ad-blocker VPN, tried each of the "ladders," and anything else I could think of, but usually only get the headline and picture - no article body (except on very rare occasions I've gotten maybe a paragraph or two).  If I send the link to an external browser, it loads up just fine. 

I really love the potential of this app, but can't seem to make it work.  Any ideas? 

OnePlus 7 Pro on Android 11.

Thanks!

**Comment by ksh-b** [comment]
What subscriptions have you selected, and is translation on.
There might be subscriptions which take time to load (like BleepingComputer).

**Comment by ksh-b** [comment]
The Wire had some issues recently and they were fixed in 0.11.0 yesterday. Please check if you are on that version.

**Comment by genga898** [comment]
I'm experiencing the same issue on Android, I've subscribed to some Engadget news feeds, the thumbnails show but the article is never loaded. I've recorded it but it's too large to attach here.

**Comment by ksh-b** [comment]
I was able to reproduce this when translation is turned on. But its fine without translation off.


![Screenshot_20240503-150529](https://github.com/ksh-b/raven/assets/24516668/00a7af30-5791-44d1-9592-b6ad8be8a1ee)

![Screenshot_20240503-150540](https://github.com/ksh-b/raven/assets/24516668/ff594ab3-d322-414e-a897-5e066a7d01d0)

**Comment by genga898** [comment]
It still doesn't work on my end, I have translations off. Here's a link to the screen recording, it's about a minute long. https://drive.google.com/file/d/1LWSiWwnunHaBmeqk-iQtVKCHQFNnMcPh/view?usp=drivesdk

**Comment by ksh-b** [comment]
@genga898 does this still happen in [0.12](https://github.com/ksh-b/raven/releases/tag/v0.12.0)

**Comment by genga898** [comment]
It loads some of the articles fully, and others it just loads the title and thumbnail image then remains in the loading state for quite a bit.
Sometimes it eventually loads the full article but most times it doesn't.

**Comment by sanctimoniousape** [comment]
Turned off translations, updated both to v0.12.1 & then v0.12.2 h both working.  Am getting up to four duplicate items (quantity varies without any seeming rhyme or reason) for many Al Jazeera stories, and occasionally Reuters stories - but otherwise everything's working at the moment. 

Thanks for the quick fix!

**Comment by ksh-b** [comment]
For whichever source you are getting duplicate, try unselecting 'Default' category

**Comment by sanctimoniousape** [comment]
I checked both sources I mentioned, and neither one had "default" selected (I don't believe that option was even there when I first set the app up).  So that doesn't appear to be the cause.
